[package]
name = "privdm"
description = "Send a Nostr Private Direct Message (NIP-17)"
version = "0.1.0"
authors = ["Ken Sedgwick <ken@bonsai.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
nostr-sdk = { version = "0.42", features = ["nip59"] }
